markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: Lihaicg 点滴生活
subTitle: 点滴记录
description: 本博客基于 Jekyll 搭建， 主题是由PIZn设计。
url: http://haicg.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 项目
    url: /works.html
  - text: 联系我
    url: http://lihaicg.dnsd.me/contact.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://lihaicg.dnsd.me
  - class: fa-facebook
    url: http://lihaicg.dnsd.me
  - class: fa-github
    url: http://github.com/haicg
  - class: fa-weibo
    url: http://weibo.com/lihaicg/
  - class: fa-renren
    url: http://lihaicg.dnsd.me
  - class: fa-pinterest
    url: http://lihaicg.dnsd.me
  - class: fa-twitter
    url: http://lihaicg.dnsd.me
  - class: fa-rss
    url: http://lihaicg.dnsd.me

#作者信息
author:
  link: http://lihaicg.dnsd.me/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin